DragonFly の layering_check を切る
TMPDIR を実 disk へ移したら grpc まで進んで、そこの module map の検査で
止まった。

	wait_for_single_owner.h:20:10: error: module
	  grpc+//src/core:wait_for_single_owner does not depend on a module
	  exporting 'absl/functional/any_invocable.h'

grpc の dep の書き漏らしで BSD とは関わりが無い。DragonFly の clang は
module map を持っているので cc_configure が layering_check を立てるが、
FreeBSD の base clang では立たないので向こうでは出ない。